server:
  port: 8080

spring:

  mvc:
    view:
      suffix: .html

  data:
    jpa:
      repositories:
        enabled: true

  datasource:
    url: jdbc:postgresql://localhost:5432/track_tagger
    username: postgres
    password: 1234

  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update

  thymeleaf:
    enabled: true
    prefix: file:src/main/resources/templates/
    suffix: .html
    cache: false

  resources:
    static-locations: file:src/main/resources/static/